title: Configuring Kubernetes kubectl in an Actions Workflow
tagline: A brand new course on Learning Lab
description: >-
  This brief course guides the student through the steps required to configure
  the Kubernetes kubectl command for use in an Actions Workflow. This lab then
  enables the student to use kubectl to deploy containerized applications to a
  live Kubernetes Cluster.
template:
  repo: configuring-kubernetes-kubectl-in-an-actions-workflow-template
  name: configuring-kubernetes-kubectl-in-an-actions-workflow
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
